/**
 *  LAXCompiler is a class that shows how a scanner generated by JFLex
 *  is running. This scanner produces instances of the class Token
 *  that can be found in the tokens directory.
 **/

package main;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import co.edu.eafit.dis.st0270.lax.lexer.LaxJFlexLexer;
import co.edu.eafit.dis.st0270.lax.tokens.Token;

public class MainLaxJFlexLexer {
    
    private static void usage(int errcode){
	System.err.println("Usage: java LaxCompiler <file>");
	System.exit(errcode);
    }
    
    public static void main(String[] args){
	
	if(args.length !=1){
	    usage(1);
	}
	
	FileInputStream fis = null;
	
	try{
	    fis = new FileInputStream(args[0]);
	} catch (FileNotFoundException fnfe) {
	    System.err.println(fnfe);
	    usage(2);
	}
	
	try {
	    LaxJFlexLexer lexer = new LaxJFlexLexer(fis);
	    
	    Token t = lexer.getNextToken();
	    while (t!=null) {
		System.out.println(t);
		t = lexer.getNextToken();
	    }
	} catch (Exception e) {
	    System.err.println(e);
	    usage(3);
	}
    }
}
